name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11

      - name: Install dependencies
        run: bun install

      - name: Build Next.js app
        run: bun run build
      
      - name: Upload to SFTP server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './build/*'
          remote_path: '/home/techcue360-milan-dev/htdocs/milan-dev.techcue360.com/'
          args: '-o ConnectTimeout=5'