name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # Deploy the built application via SFTP
      - name: Deploy to Server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          
          # Local path - Next.js build output (using your custom distDir)
          local_path: './build/*'
          
          # Remote path - your server directory
          remote_path: '/home/techcue360-milan-dev/htdocs/milan-dev.techcue360.com/'
          
          # SFTP arguments
          args: '-o ConnectTimeout=5'
