name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11

      - name: Install dependencies
        run: bun install

      - name: Build Next.js app
        run: bun run build

      # Debug: Check build output
      - name: List build directory
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Build directory size:"
          du -sh build/

      # Debug: Test server connectivity
      - name: Test server connectivity
        run: |
          echo "Testing connectivity to server..."
          ping -c 3 ${{ secrets.FTP_SERVER }} || echo "Ping failed"
          echo "Testing SSH/SFTP port (22)..."
          nc -zv ${{ secrets.FTP_SERVER }} 22 || echo "Port 22 not accessible"
          echo "Testing FTP port (21)..."
          nc -zv ${{ secrets.FTP_SERVER }} 21 || echo "Port 21 not accessible"

      - name: Upload to server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './build/*'
          remote_path: '/home/techcue360-milan-dev/htdocs/milan-dev.techcue360.com/'
          args: '-o ConnectTimeout=5'