name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # Debug: List build contents
      - name: List build directory contents
        run: |
          echo "Contents of build directory:"
          ls -la build/
          echo "Total size:"
          du -sh build/

      # Deploy the built application via SFTP
      - name: Deploy to Server via SFTP
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: /home/techcue360-milan-dev/htdocs/milan-dev.techcue360.com/
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          concurrency: 20
